# Generated by Django 4.1 on 2024-11-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_touristattraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristattraction',
            old_name='location',
            new_name='mpoint',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='description',
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='tourism',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
