# Generated by Django 4.1 on 2024-11-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_rename_location_touristattraction_mpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristattraction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='country',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='street',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='tourism',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='website',
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
