# Generated by Django 4.1 on 2024-11-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_remove_touristattraction_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='opening_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='tourism',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touristattraction',
            name='wheelchair',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
