# Generated by Django 4.1 on 2024-11-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_touristattraction_address_touristattraction_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristattraction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='touristattraction',
            name='wheelchair',
        ),
    ]
